### PR TITLE
Python3

### LINKED ISSUE #31: Support python3
We should support python3. We're currently explicitly requiring python2.7 and do not test with python3. As far as we know all our current dependencies support python3. cuckoo itself does not (yet) but we only spawn it as a process and do not load any modules from it. Insofar we "only" need to look at our own code.

Suggested by @SebastianDeiss.

### PR DESCRIPTION
**Pull request by michaelweiser**
Put the final touches to working python3 support.

Closes #31.

### CODE REVIEW

**Comment by Jack28** [comment]
```
~/PeekabooAV# ./setup.py install
/usr/bin/env: 'python': No such file or directory
```
should we reference python3 here?

**Comment by michaelweiser** [comment]
Huh, I do have `/usr/bin/python` and every Linux system I've seen has it if python is installed at all. On Ubuntu it's provided by package `python-minimal` and a symlink to `python2.7` and trying to uninstall it would also pull the `python` package and all its dependencies. So it seems to be a fundamental dependency for all python2 packages.

Can you check how you lost or never got that symlink `/usr/bin/python`?

**Comment by Jack28** [comment]
It's the ubuntu docker container, 100% my fault.
I only installed python3, no symlink here.

This is more a religious question I guess, whether we should specifically require python3 or support both. Since python3 is not the standard yet

**Comment by michaelweiser** [comment]
Unfortunately we can't (or shan't :) do conditionals in the shebang like `#!/usr/bin/env python2 || /usr/bin/env python3`. That's why there's usually a symlink `/usr/bin/python` pointing to the default and "best" version.

On Ubuntu it does not seem to be intended to be switched to point to python3 by the user (at least I could find no reference to it while e.g. Gentoo has a mechanism for just that). Rather it is managed by the `python-minimal` package. So if that package during the lifetime of Ubuntu 18.04 were ever to switch the symlink from python2 to python3 it would basically declare that version the new "best" and default version. I think that's not likely to happen.

So I'd argue, `/usr/bin/env python` does exactly what we want: It uses the system's default best python interpreter as a (hopefully) sane default to run our software which is compatible with both major releases.

In the meantime, the user can force the version by running `python3 setup.py install`, `virtualenv --python3` or `pip3 install peekabooav`, with virtualenv giving them a new `/venv/bin/python` symlink statically pointing to the right version and pip3 even creating a `peekaboo` wrapper with the right shebang set statically. I'm currently working on implementing just that in the Installer. This might then also work in that special case where `/usr/bin/python` is missing.

Once we decide to drop python2 support entirely this reasoning might change. Then we will likely need to switch to python3 in the shebang to be on the safe side regarding misleading error messages to the user because his `/usr/bin/python` is still pointing to python2. But since we currently actually don't care about the interpreter version, I'd opt to forgo  that for now.

**Comment by Jack28** [comment]
I agree

**Pull request merged**
