### PR TITLE
ci: Add GitHub Actions and compose-based CI

### PR DESCRIPTION
**Pull request by michaelweiser**
Add an initial GitHub Actions workflow that checks out the PeekabooAV-Installer and PeekabooAV repos in the correct structure to then run docker-compose to bring up a CI pipeline for validation.

This is WIP as it still uses my fork and non-merged branches there. It's to discuss the way to go and work on it together.

@Sett17 : fyi

### CODE REVIEW

**Comment by michaelweiser** [comment]
Should we have a scheduled run to catch changing dependencies causing incompatibilities?
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule

**Comment by michaelweiser** [comment]
Rebased to master and named the scheduled testsuite build jobs more clearly to reflect that they're supposed to be groups of branches that can be tested the same way.

**Comment by michaelweiser** [comment]
Added a simple test job to the container ci job to verify peekaboo and cortex are working.

**Review by Jack28 — APPROVED** [review]
LGTM
I am amazed

**Pull request merged**
