### PR TITLE
2.1rc2 prep

### PR DESCRIPTION
**Pull request by michaelweiser**
This mainly removes our dependency on cortex4py (for the time being) so we can release 2.1. While at it we also remove the mostly annoying startup availability checks of the Cuckoo and Cortex APIs.

### CODE REVIEW

**Comment by michaelweiser** [comment]
For some reason Travis python 3.7 can't install sdnotify today. Github Actions work: https://github.com/michaelweiser/PeekabooAV/actions/runs/2016371506

**Comment by Jack28** [comment]
Nice, good job.

While you're on it, can you fix `WARNING - Report returned from Cortex contained invalid data: Subclass needs to provide a schema` for class `CuckooSandboxFileAnalysisReport`?

**Comment by michaelweiser** [comment]
> Nice, good job.
> 
> While you're on it, can you fix `WARNING - Report returned from Cortex contained invalid data: Subclass needs to provide a schema` for class `CuckooSandboxFileAnalysisReport`?

I'm struggling to get a testing setup with Cortex and Cuckoo going. Can we postpone this to RC3 or 2.2?

**Review by Jack28 — APPROVED** [review]
LGTM

**Pull request merged**
